-- AlterEnum
ALTER TYPE "SyncTarget" ADD VALUE 'GOOGLE_GROUP';

-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'GOOGLE_GROUP_SYNCED';

-- AlterTable
ALTER TABLE "AuditLog" ALTER COLUMN "targetId" DROP NOT NULL;
