import type {
  AppLinkAccent,
  MembershipStatus,
} from "../app/generated/prisma/client";
import type { ComputerMetadata } from "../lib/services/computer-schemas";
import type { AppLinkIconName } from "../types";

// The fallback UUIDs are invented, so a default seed never points at a real Authentik instance.
// Real ones belong in `.dev-authentik-groups.json` (gitignored) — see scripts/dev-groups.ts.
export const SEED_GROUPS = {
  CHIEF_EDITOR: {
    displayName: "Főszerkesztő",
    fallbackId: "0a7c1d3e-5b42-4f18-9c6a-2d81e4f70b35",
  },
  PRODUCTION: {
    displayName: "Gyártásvezető",
    fallbackId: "1c94f6a2-8d37-4b5e-a021-7f3c9e5d84b6",
  },
  PR: {
    displayName: "PR-felelős",
    fallbackId: "2e5d8b70-3a19-4c6f-b842-95d1f0c7a3e8",
  },
} as const satisfies Record<
  string,
  { displayName: string; fallbackId: string }
>;

export type SeedGroupKey = keyof typeof SEED_GROUPS;

export interface SeedMember {
  firstName: string;
  lastName: string;
  nickname: string | null;
  university: string | null;
  major: string | null;
  dormRoom: string | null;
  status: MembershipStatus;
  joinedSemestersAgo: number;
  archivedSemestersAgo?: number;
  /** Not every leadership title has an Authentik group — `groups: []` is the common case. */
  role?: { label: string; groups: SeedGroupKey[] };
}

// Invented people. Hungarian given names and surnames paired at random — no real member here.
export const SEED_MEMBERS: SeedMember[] = [
  {
    firstName: "Máté",
    lastName: "Boros",
    nickname: null,
    university: "BME",
    major: "VIK",
    dormRoom: "A301",
    status: "MEMBER_CANDIDATE_CANDIDATE",
    joinedSemestersAgo: 0,
  },
  {
    firstName: "Csenge",
    lastName: "Halász",
    nickname: "Csengi",
    university: "BME",
    major: "GPK",
    dormRoom: "B102",
    status: "MEMBER_CANDIDATE_CANDIDATE",
    joinedSemestersAgo: 0,
  },
  {
    firstName: "Levente",
    lastName: "Vincze",
    nickname: null,
    university: "ELTE",
    major: "IK",
    dormRoom: "C205",
    status: "MEMBER_CANDIDATE_CANDIDATE",
    joinedSemestersAgo: 0,
  },
  {
    firstName: "Panna",
    lastName: "Bogdán",
    nickname: null,
    university: "BME",
    major: "VIK",
    dormRoom: "A402",
    status: "MEMBER_CANDIDATE_CANDIDATE",
    joinedSemestersAgo: 0,
  },
  {
    firstName: "Ádám",
    lastName: "Szalai",
    nickname: null,
    university: "BME",
    major: "VIK",
    dormRoom: "A101",
    status: "MEMBER_CANDIDATE",
    joinedSemestersAgo: 0,
  },
  {
    firstName: "Enikő",
    lastName: "Fodor",
    nickname: "Eni",
    university: "ELTE",
    major: "BTK",
    dormRoom: null,
    status: "MEMBER_CANDIDATE",
    joinedSemestersAgo: 0,
  },
  {
    firstName: "Zalán",
    lastName: "Barta",
    nickname: null,
    university: "BME",
    major: "GPK",
    dormRoom: "B203",
    status: "MEMBER_CANDIDATE",
    joinedSemestersAgo: 0,
  },
  {
    firstName: "Fanni",
    lastName: "Somogyi",
    nickname: "Fanni",
    university: "SZFE",
    major: null,
    dormRoom: null,
    status: "MEMBER_CANDIDATE",
    joinedSemestersAgo: 0,
  },
  {
    firstName: "Botond",
    lastName: "Kocsis",
    nickname: "Boti",
    university: "BME",
    major: "VIK",
    dormRoom: "A304",
    status: "MEMBER_CANDIDATE",
    joinedSemestersAgo: 1,
  },
  {
    firstName: "Zsombor",
    lastName: "Pintér",
    nickname: "Zsomi",
    university: "BME",
    major: "VIK",
    dormRoom: "A205",
    status: "MEMBER",
    joinedSemestersAgo: 3,
    role: { label: "Stúdióvezető", groups: [] },
  },
  {
    firstName: "Domonkos",
    lastName: "Sipos",
    nickname: null,
    university: "BME",
    major: "GPK",
    dormRoom: "B306",
    status: "MEMBER",
    joinedSemestersAgo: 3,
  },
  {
    firstName: "Gergő",
    lastName: "Katona",
    nickname: null,
    university: "BME",
    major: "VIK",
    dormRoom: "A407",
    status: "MEMBER",
    joinedSemestersAgo: 5,
    role: { label: "Főszerkesztő", groups: ["CHIEF_EDITOR"] },
  },
  {
    firstName: "László",
    lastName: "Bodnár",
    nickname: null,
    university: "ELTE",
    major: "IK",
    dormRoom: null,
    status: "MEMBER",
    joinedSemestersAgo: 2,
  },
  {
    firstName: "Emma",
    lastName: "Vámosi",
    nickname: "Emmi",
    university: "BME",
    major: "ÉPK",
    dormRoom: "C108",
    status: "MEMBER",
    joinedSemestersAgo: 4,
    role: { label: "Stúdióvezető-helyettes", groups: [] },
  },
  {
    firstName: "Réka",
    lastName: "Deák",
    nickname: null,
    university: "BCE",
    major: null,
    dormRoom: null,
    status: "MEMBER",
    joinedSemestersAgo: 3,
  },
  {
    firstName: "Sára",
    lastName: "Gulyás",
    nickname: "Sári",
    university: "ELTE",
    major: "TTK",
    dormRoom: "D209",
    status: "MEMBER",
    joinedSemestersAgo: 5,
    role: { label: "PR-felelős", groups: ["PR"] },
  },
  {
    firstName: "Viktor",
    lastName: "Fekete",
    nickname: "Viki",
    university: "BME",
    major: "VIK",
    dormRoom: "A310",
    status: "MEMBER",
    joinedSemestersAgo: 2,
  },
  {
    firstName: "Balázs",
    lastName: "Jakab",
    nickname: null,
    university: "BME",
    major: "GPK",
    dormRoom: "B411",
    status: "MEMBER",
    joinedSemestersAgo: 4,
    role: { label: "Oktatásfelelős", groups: [] },
  },
  {
    firstName: "Bence",
    lastName: "Király",
    nickname: null,
    university: "BME",
    major: "VIK",
    dormRoom: "A112",
    status: "MEMBER",
    joinedSemestersAgo: 5,
    role: { label: "Technikai vezető", groups: [] },
  },
  {
    firstName: "Áron",
    lastName: "Szűcs",
    nickname: null,
    university: "BME",
    major: "TTK",
    dormRoom: "C213",
    status: "MEMBER",
    joinedSemestersAgo: 2,
  },
  {
    firstName: "Kincső",
    lastName: "Fülöp",
    nickname: "Kincsi",
    university: "ELTE",
    major: "BTK",
    dormRoom: null,
    status: "MEMBER",
    joinedSemestersAgo: 4,
  },
  {
    firstName: "Barnabás",
    lastName: "Orosz",
    nickname: null,
    university: "BME",
    major: "VIK",
    dormRoom: "A314",
    status: "MEMBER",
    joinedSemestersAgo: 5,
  },
  {
    firstName: "Marcell",
    lastName: "Sándor",
    nickname: "Marci",
    university: "BME",
    major: "VIK",
    dormRoom: "A215",
    status: "MEMBER",
    joinedSemestersAgo: 3,
    role: { label: "Gyártásvezető", groups: ["PRODUCTION"] },
  },
  {
    firstName: "Benedek",
    lastName: "Lengyel",
    nickname: "Beni",
    university: "BME",
    major: "GPK",
    dormRoom: "B116",
    status: "MEMBER",
    joinedSemestersAgo: 4,
  },
  {
    firstName: "Blanka",
    lastName: "Torma",
    nickname: null,
    university: "BCE",
    major: null,
    dormRoom: null,
    status: "MEMBER",
    joinedSemestersAgo: 1,
  },
  {
    firstName: "Villő",
    lastName: "Szentesi",
    nickname: null,
    university: "Semmelweis",
    major: "ÁOK",
    dormRoom: null,
    status: "MEMBER",
    joinedSemestersAgo: 2,
  },
  {
    firstName: "Dominik",
    lastName: "Vass",
    nickname: "Dom",
    university: "BME",
    major: "VIK",
    dormRoom: null,
    status: "ACTIVE_ALUMNI",
    joinedSemestersAgo: 9,
  },
  {
    firstName: "Tamás",
    lastName: "Illés",
    nickname: null,
    university: "BME",
    major: "GPK",
    dormRoom: null,
    status: "ACTIVE_ALUMNI",
    joinedSemestersAgo: 10,
  },
  {
    firstName: "Krisztián",
    lastName: "Márton",
    nickname: "Krisz",
    university: "BME",
    major: "VIK",
    dormRoom: null,
    status: "ACTIVE_ALUMNI",
    joinedSemestersAgo: 9,
  },
  {
    firstName: "Dorina",
    lastName: "Székely",
    nickname: "Dodó",
    university: "ELTE",
    major: "BTK",
    dormRoom: null,
    status: "ACTIVE_ALUMNI",
    joinedSemestersAgo: 11,
  },
  {
    firstName: "Gergely",
    lastName: "Antal",
    nickname: "Gergő",
    university: "BME",
    major: "VIK",
    dormRoom: null,
    status: "ACTIVE_ALUMNI",
    joinedSemestersAgo: 13,
  },
  {
    firstName: "Dániel",
    lastName: "Csizmadia",
    nickname: "Dani",
    university: "BME",
    major: "TTK",
    dormRoom: null,
    status: "ACTIVE_ALUMNI",
    joinedSemestersAgo: 10,
  },
  {
    firstName: "Henrik",
    lastName: "Pásztor",
    nickname: null,
    university: "Óbudai Egyetem",
    major: "NIK",
    dormRoom: null,
    status: "ACTIVE_ALUMNI",
    joinedSemestersAgo: 14,
  },
  {
    firstName: "Nóra",
    lastName: "Kelemen",
    nickname: null,
    university: "BCE",
    major: null,
    dormRoom: null,
    status: "ACTIVE_ALUMNI",
    joinedSemestersAgo: 11,
  },
  {
    firstName: "Kornél",
    lastName: "Bakos",
    nickname: null,
    university: "BME",
    major: "VIK",
    dormRoom: null,
    status: "ALUMNI",
    joinedSemestersAgo: 19,
  },
  {
    firstName: "Dávid",
    lastName: "Csonka",
    nickname: null,
    university: "BME",
    major: "GPK",
    dormRoom: null,
    status: "ALUMNI",
    joinedSemestersAgo: 21,
  },
  {
    firstName: "Márton",
    lastName: "Gaál",
    nickname: null,
    university: "BME",
    major: "VIK",
    dormRoom: null,
    status: "ALUMNI",
    joinedSemestersAgo: 19,
  },
  {
    firstName: "Gergely",
    lastName: "Hajdú",
    nickname: "Gergő",
    university: "ELTE",
    major: "IK",
    dormRoom: null,
    status: "ALUMNI",
    joinedSemestersAgo: 22,
  },
  {
    firstName: "Judit",
    lastName: "Balla",
    nickname: null,
    university: "BME",
    major: "TTK",
    dormRoom: null,
    status: "ALUMNI",
    joinedSemestersAgo: 23,
  },
  {
    firstName: "Attila",
    lastName: "Veres",
    nickname: null,
    university: "BME",
    major: "VIK",
    dormRoom: null,
    status: "MEMBER",
    joinedSemestersAgo: 16,
    archivedSemestersAgo: 8,
  },
  {
    firstName: "Ilona",
    lastName: "Novák",
    nickname: null,
    university: "ELTE",
    major: "BTK",
    dormRoom: null,
    status: "ALUMNI",
    joinedSemestersAgo: 25,
    archivedSemestersAgo: 4,
  },
  {
    firstName: "Norbert",
    lastName: "Molnár",
    nickname: null,
    university: "BME",
    major: "GPK",
    dormRoom: null,
    status: "MEMBER_CANDIDATE",
    joinedSemestersAgo: 6,
    archivedSemestersAgo: 5,
  },
];

// Plausible rather than authoritative: dev data, same as the invented members above.
export interface SeedAppLink {
  name: string;
  description: string | null;
  url: string;
  icon: AppLinkIconName;
  accent: AppLinkAccent;
  featured?: boolean;
}

export const SEED_APP_LINKS: SeedAppLink[] = [
  {
    name: "Weboldal",
    description: "A stúdió publikus oldala",
    url: "https://bsstudio.hu",
    icon: "globe",
    accent: "BLUE",
    featured: true,
  },
  {
    name: "Wiki",
    description: "Dokumentáció és jegyzőkönyvek",
    url: "https://wiki.bsstudio.hu",
    icon: "book-open",
    accent: "TEAL",
    featured: true,
  },
  {
    name: "Kérelemkezelő",
    description: "Forgatási kérelmek",
    url: "https://request.bsstudio.hu",
    icon: "clipboard-list",
    accent: "GREEN",
    featured: true,
  },
  {
    name: "Authentik",
    description: "Fiók és jelszó",
    url: "https://auth.bsstudio.hu",
    icon: "shield-check",
    accent: "ORANGE",
  },
  {
    name: "Felhő",
    description: "Közös fájltár",
    url: "https://cloud.bsstudio.hu",
    icon: "cloud",
    accent: "VIOLET",
  },
  {
    name: "Naptár",
    description: "Forgatások és események",
    url: "https://calendar.google.com",
    icon: "calendar",
    accent: "RED",
  },
  {
    name: "Levelezés",
    description: "A stúdió postafiókja",
    url: "https://mail.google.com",
    icon: "mail",
    accent: "AMBER",
  },
  {
    name: "Gépfoglalás",
    description: null,
    url: "https://foglalas.bsstudio.hu",
    icon: "monitor",
    accent: "PINK",
  },
];

export interface SeedComputer {
  id: string;
  minutesAgo: number;
  metadata: ComputerMetadata;
}

// The three edit stations, between them covering every state a card renders: in use,
// signed in but locked (which the portal reads as free), and offline.
export const SEED_COMPUTERS: SeedComputer[] = [
  {
    id: "nle4",
    minutesAgo: 0,
    metadata: {
      os: "Microsoft Windows 11 Pro",
      cpuPercent: 34,
      memoryPercent: 61,
      diskPercent: 88,
      loggedInUser: "BSS\\nkovacs",
      locked: false,
      agentVersion: "v1.1.1",
    },
  },
  {
    id: "nle6",
    minutesAgo: 1,
    metadata: {
      os: "Microsoft Windows 11 Pro",
      cpuPercent: 2,
      memoryPercent: 24,
      diskPercent: 41,
      loggedInUser: "BSS\\aszabo",
      locked: true,
      agentVersion: "v1.1.1",
    },
  },
  // Offline, and left on an older agent so the version drift the ping reports is visible.
  {
    id: "nle7",
    minutesAgo: 240,
    metadata: {
      os: "Microsoft Windows 11 Pro",
      loggedInUser: null,
      agentVersion: "v1.1.0",
    },
  },
];
